### ISSUE TITLE
Using JuMP v0.20 and MOI for `maximum_weight_matching`

### ISSUE THREAD

**Issue by Wikunia** [JuliaGraphs/LightGraphsMatching.jl#14]
Currently the `maximum_weight_matching` function doesn't work with the latest JuMP version using MOI.
I'll work on that so maybe someone can assign me to it ;)

**Comment by matbesancon** [comment]
@JuliaRegistrator register()

**Comment by Wikunia** [comment]
The UUID in the registry is: `160ba089-64bf-5ba7-9e14-98ab1d9bcb0a`
https://github.com/JuliaRegistries/General/blob/master/L/LightGraphsMatching/Package.toml

**Comment by matbesancon** [comment]
@JuliaRegistrator register()
